artifact_location: /home/santiago-sanchez/Escritorio/eibais-mlops-excercise/MLFLOW_TRACKING_URI=https:/dagshub.com/SntSca/eibais-mlops-excercise.mlflow/0
creation_time: 1747130266273
experiment_id: '0'
last_update_time: 1747130266273
lifecycle_stage: active
name: Default
