artifact_uri: /home/santiago-sanchez/Escritorio/eibais-mlops-excercise/MLFLOW_TRACKING_URI=https:/dagshub.com/SntSca/eibais-mlops-excercise.mlflow/0/a39d53c791494fd28a0a1fe2a6450466/artifacts
end_time: 1747131464375
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: a39d53c791494fd28a0a1fe2a6450466
run_name: /home/santiago-sanchez/Escritorio/eibais-mlops-excercise/models/distilbert-twitter-emotions-checkpoint
run_uuid: a39d53c791494fd28a0a1fe2a6450466
source_name: ''
source_type: 4
source_version: ''
start_time: 1747131451081
status: 3
tags: []
user_id: SntSca
