artifact_uri: /home/santiago-sanchez/Escritorio/eibais-mlops-excercise/MLFLOW_TRACKING_URI=https:/dagshub.com/SntSca/eibais-mlops-excercise.mlflow/0/e54944303b6044efbbc9c3e4b9b99c7b/artifacts
end_time: 1747131823314
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: e54944303b6044efbbc9c3e4b9b99c7b
run_name: /home/santiago-sanchez/Escritorio/eibais-mlops-excercise/models/distilbert-twitter-emotions-checkpoint
run_uuid: e54944303b6044efbbc9c3e4b9b99c7b
source_name: ''
source_type: 4
source_version: ''
start_time: 1747131810041
status: 3
tags: []
user_id: SntSca
